USE [master]
GO
/****** Object:  Database [GameManager]    Script Date: 10/10/2025 4:38:11 PM ******/
CREATE DATABASE [GameManager]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CrudWindowsForm', FILENAME = N'C:\repos\db\GameManager.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CrudWindowsForm_log', FILENAME = N'C:\repos\db\GameManager_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [GameManager] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GameManager].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GameManager] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GameManager] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GameManager] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GameManager] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GameManager] SET ARITHABORT OFF 
GO
ALTER DATABASE [GameManager] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [GameManager] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GameManager] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GameManager] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GameManager] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GameManager] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GameManager] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GameManager] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GameManager] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GameManager] SET  DISABLE_BROKER 
GO
ALTER DATABASE [GameManager] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GameManager] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GameManager] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GameManager] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GameManager] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GameManager] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GameManager] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GameManager] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [GameManager] SET  MULTI_USER 
GO
ALTER DATABASE [GameManager] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GameManager] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GameManager] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GameManager] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [GameManager] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GameManager] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'GameManager', N'ON'
GO
ALTER DATABASE [GameManager] SET QUERY_STORE = OFF
GO
ALTER DATABASE [GameManager] SET  READ_WRITE 
GO
